# Generated by Django 4.1.7 on 2023-05-10 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('branch', models.CharField(choices=[('Palakkad', (('1', 'otp'), ('2', 'ptb'))), ('Thrissur', (('3', 'chr'), ('4', 'iri')))], max_length=50)),
                ('account_type', models.CharField(choices=[('1', 'current account'), ('2', 'savings account'), ('3', 'join account')], max_length=50)),
                ('materials_provided', models.BooleanField(choices=[('1', 'Debit card'), ('2', 'Chequebook')], max_length=50)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sampleapp.districts')),
            ],
        ),
    ]
