# Generated by Django 4.1.7 on 2023-05-10 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0002_remove_personaldetails_materials_provided_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaldetails',
            old_name='Cheque Book',
            new_name='materials_provided',
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='materials_provided2',
            field=models.BooleanField(default=False, verbose_name='Cheque Book'),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='materials_provided3',
            field=models.BooleanField(default=False, verbose_name='Credit Card'),
        ),
    ]
