# Generated by Django 4.1.7 on 2023-05-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0003_rename_cheque book_personaldetails_materials_provided_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='branch',
            field=models.CharField(choices=[('Kannur', (('1', 'Thaliparambu'), ('2', 'Payyannur'))), ('Kozhikode', (('1', 'Vadakara'), ('2', 'Perambra'))), ('Malappuram', (('1', 'Tirur'), ('2', 'Edappal'))), ('Palakkad', (('1', 'Ottapalam'), ('2', 'Pattambi'))), ('Thrissur', (('3', 'Cheruthuruthi'), ('4', 'Kunnamkulam')))], max_length=50),
        ),
    ]
